### ISSUE TITLE
BasicMapTool properties does not exist

### ISSUE THREAD

**Issue by rdan461** [Esri/contributing#22]
I'm using VS 2015 Professional with ArcGIS Pro SDK 2; building the BasicMapTool project returns errors for OverlayControlCanResize and OverlayControlPositionRatio, says the name does not exist in the current context.  These are not properties of the OverlayControl....

        public BasicMapTool() : base() {
            this.OverlayControlID = "BasicMapTool_BasicEmbeddableControl";
           

            //Embeddable control can be resized
           OverlayControlCanResize = true;
           // //Specify ratio of 0 to 1 to place the control
           OverlayControlPositionRatio = new System.Windows.Point(0, 0); //top left
        }

**Comment by jgravois** [comment]
greetings @rdan461 👋

i'm pretty much the only one keeping an eye on this repo right now, and i haven't written any C# in _many_ years.

because of this, my best suggestion is for you to ask your question on Geonet in the [ArcGIS Pro SDK](https://community.esri.com/groups/arcgis-pro-sdk) community or perhaps https://github.com/Esri/arcgis-pro-sdk.

**Comment by rdan461** [comment]
Thanks for the info.

Rich Daniels
GIS Product Support Coordinator & CAFM/IRIS Support
ITD, WSDOT
(360) 705-7654
